services:
  site:
    build: .
    volumes:
      - ".:/site"
    ports:
      - "8000:8000"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ./storage/minio:/data
    environment:
      MINIO_ROOT_USER: "bastilian"
      MINIO_ROOT_PASSWORD: "miniopass"
      MINIO_VOLUMES: "/mnt/data"
      # MINIO_ACCESS_KEY: "minio_access_key"
      # MINIO_SECRET_KEY: "minio_secret_key"
    command: server --console-address ":9090" --address 0.0.0.0:9000 /data
